rules: []
rulesConfigs: []
hooks: []
pages: []
resourceServers: []
clients: []
databases: []
connections: []
tenant:
  default_audience: ''
  default_directory: ''
  enabled_locales:
    - en
  flags:
    revoke_refresh_token_grant: false
    disable_clickjack_protection_headers: false
  friendly_name: ''
  idle_session_lifetime: 72
  picture_url: ''
  sandbox_version: '18'
  session_cookie:
    mode: non-persistent
  session_lifetime: 168
  support_email: ''
  support_url: ''
  universal_login:
    colors:
      page_background: '#000000'
      primary: '#EA5323'
    passwordless:
      allow_magiclink_verify_without_session: true
emailProvider: {}
emailTemplates: []
clientGrants: []
guardianFactors: []
guardianFactorProviders: []
guardianFactorTemplates: []
guardianPolicies:
  policies: []
guardianPhoneFactorSelectedProvider: {}
guardianPhoneFactorMessageTypes: {}
roles: []
branding:
  colors:
    page_background: '#000000'
    primary: '#EA5323'
  logo_url: ''
  templates: []
prompts:
  customText: {}
  identifier_first: true
  universal_login_experience: new
  webauthn_platform_first_factor: false
migrations: {}
actions: []
triggers: {}
organizations: []
attackProtection:
  breachedPasswordDetection:
    enabled: false
    shields:
      - block
      - user_notification
      - admin_notification
    admin_notification_frequency:
      - immediately
    method: standard
    stage:
      pre-user-registration:
        shields: []
  bruteForceProtection:
    enabled: true
    shields:
      - block
      - user_notification
    mode: count_per_identifier
    allowlist: []
    max_attempts: 10
  suspiciousIpThrottling:
    enabled: true
    shields:
      - admin_notification
      - block
    allowlist: []
    stage:
      pre-login:
        max_attempts: 100
        rate: 864000
      pre-user-registration:
        max_attempts: 50
        rate: 1200
logStreams: []
customDomains: []
themes: []
